[package]
name = "lv2plugins"
version = "0.1.0"
authors = ["Michael Oswald <michael.oswald@onikudaki.net>"]

[dependencies]
libc = "0.2.21"
lv2_raw = "0.1.0"
num = "0.1.37"

[lib]
name = "rustamp"
crate-type = ["dylib"] # ?

