[package]
name = "lv2plugins"
version = "0.1.0"
authors = ["Michael Oswald <michael.oswald@onikudaki.net>"]

[dependencies]
libc = "0.2.21"
num = "0.1.37"

[dependencies.lv2_raw]
path = "../../lv2_raw"

[lib]
name = "rustmetro"
crate-type = ["dylib"] # ?

